## Basic Configuration

baseurl = "https://zhenfeng-zhu.github.io" 
builddrafts = false
canonifyurls = false
languageCode = "zh-CN"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Lucas"
title = "Lucas"

theme = "goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Lucas"
intro = "独立思考 / 程序员 / 执着 / 小说控 / 好交益友"
description = "毕业于北京邮电大学(数字媒体技术专业)，目前就职于Finogeeks(深圳)，主要负责后台开发。"
authorimage = "mywechat.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Lucas's blog"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "zhenfeng-zhu"
instagram = "<username>"
# xing = "<username>"
linkedin = "<username>"
twitter = "<username>"
facebook = "<username>"
google = "<username>"
stackoverflow = "<username>"
email = "codeless98@163.com"

## Extras
[params.extra]
copyright = "© 2018. Lucas. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = false
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blogs/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "gallery"
    identifier = "gallery"
    weight = 300
    url = "/gallery/"

